name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Upload artifact?'
        required: false
        type: boolean

  push:
    branches:
      - 'sep-15/ksu'
      - 'sep-15/connectivity'
      - 'sep-15/stock'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get full-upgrade -y
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev --install-recommends


    - name: Download toolchain
      run: |
        wget "https://android.googlesource.com/platform//prebuilts/clang/host/linux-x86/+archive/refs/tags/android-12.0.0_r1/clang-r383902.tar.gz"
        mkdir -p toolchain/clang/host/linux-x86/clang-r383902
        tar -xzf clang-r383902.tar.gz -C toolchain/clang/host/linux-x86/clang-r383902/
        rm clang-r383902.tar.gz

    - name: Build kernel
      run: |
        bash build_kernel.sh

    - name: Download magiskboot utility
      run: |
        wget https://github.com/topjohnwu/Magisk/releases/latest/download/Magisk-v26.4.apk -O magisk.zip
        unzip magisk.zip lib/x86_64/*
        chmod +x lib/x86_64/*
        sudo mv lib/x86_64/libbusybox.so /usr/bin/busybox
        sudo mv lib/x86_64/libmagiskboot.so /usr/bin/magiskboot

    - name: Build boot.img
      run: |
        wget https://github.com/Fede2782/proprietary_vendor_samsung_a34x/releases/latest/download/boot.img -O stock_boot.img
        mkdir unpacked && cd unpacked
        magiskboot unpack ../stock_boot.img
        mv ../arch/arm64/boot/Image kernel
        PATCHVBMETAFLAG=true magiskboot repack ../stock_boot.img
        mv new-boot.img ../boot.img && cd ..


    - name: Upload image
      if: ${{ github.event.inputs.choice == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: artifact-name
        path: |
           arch/arm64/boot/Image
           boot.img
